### ISSUE TITLE
Centrer les boutons

### ISSUE THREAD

**Issue by edenpulse** [edenpulse/hairy-octo-computing-machine#5]
Ce serait mieux de centrer les boutons "voir le programme" et "inscription" sous le texte d'intro
comme ceci 
http://cl.ly/ZjvO
(only sur smartphone)

**Comment by creativejuiz** [comment]
L'élément juste avant et l'élément juste après sont ferrés à gauche, ça fait bizarre si les boutons se la joue perso :)

**Comment by edenpulse** [comment]
Vendu. thanks !
