### ISSUE TITLE
Centrer les portraits orateurs

### ISSUE THREAD

**Issue by edenpulse** [edenpulse/hairy-octo-computing-machine#6]
Je pense qu'ajouter un peu de marge en haut et en bas des portraits ronds des orateurs serait plus sympa. Et les centrer. ( margin:auto style )
(only sur smartphone)

**Comment by creativejuiz** [comment]
Ok pour la marge. Par contre si je centre la photo, il faut que je centre le nom de la conf et le nom de l'orateur sinon ça fait lecture zigzag, pas joyeux. Ferré à gauche avec de la marge ça le fait. Je commit/push/pull request :p

**Comment by edenpulse** [comment]
Je te fais confiance :) Merci !
